spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apifactory
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
server:
  port: 8080
